In [5]:
import numpy as np
import math

In [6]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# Problem 1
Matrix product, manually  

In [33]:
## matrix multiplication 
## matrix product, has the number of rows of the first and the number of columns of the second matrix
## c_i_j (i-th row j-th column element of c array) is the dot product of the a's i-th row and b's j-th column
c_array1=[[0,0,0],[0,0,0],[0,0,0]]
c_array1[0][0] = a_ndarray[0][0]*b_ndarray[0][0]+a_ndarray[0][1]*b_ndarray[1][0]+a_ndarray[0][2]*b_ndarray[2][0]
c_array1[0][1] = a_ndarray[0][0]*b_ndarray[0][1]+a_ndarray[0][1]*b_ndarray[1][1]+a_ndarray[0][2]*b_ndarray[2][1]
c_array1[0][2] = a_ndarray[0][0]*b_ndarray[0][2]+a_ndarray[0][1]*b_ndarray[1][2]+a_ndarray[0][2]*b_ndarray[2][2]
c_array1[1][0] = a_ndarray[1][0]*b_ndarray[0][0]+a_ndarray[1][1]*b_ndarray[1][0]+a_ndarray[1][2]*b_ndarray[2][0]
c_array1[1][1] = a_ndarray[1][0]*b_ndarray[0][1]+a_ndarray[1][1]*b_ndarray[1][1]+a_ndarray[1][2]*b_ndarray[2][1]
c_array1[1][2] = a_ndarray[1][0]*b_ndarray[0][2]+a_ndarray[1][1]*b_ndarray[1][2]+a_ndarray[1][2]*b_ndarray[2][2]
c_array1[2][0] = a_ndarray[2][0]*b_ndarray[0][0]+a_ndarray[2][1]*b_ndarray[1][0]+a_ndarray[2][2]*b_ndarray[2][0]
c_array1[2][1] = a_ndarray[2][0]*b_ndarray[0][1]+a_ndarray[2][1]*b_ndarray[1][1]+a_ndarray[2][2]*b_ndarray[2][1]
c_array1[2][2] = a_ndarray[2][0]*b_ndarray[0][2]+a_ndarray[2][1]*b_ndarray[1][2]+a_ndarray[2][2]*b_ndarray[2][2]
np.array(c_array1)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

Note for code above:
Previously, I wrote and used the code on Problem 3 in here, but it appears we use loop in the Problem 3. Therefore, copied the code there and changed this code. In the instuction it was "by hand", so I thought element-wise multiplication and addition should be done here, like we do on the paper.

# Problem 2
use function

In [16]:
c_array2 = np.matmul(a_ndarray,b_ndarray)
c_array2

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

# Problem 3
code for matrix multiplication without using matmul() or dot() 

In [30]:
c_array3 = [[0,0,0],
            [0,0,0],
            [0,0,0]]
for i in range(len(a_ndarray)):
   for j in range(len(b_ndarray[0])):
       for k in range(len(b_ndarray)):
            c_array3[i][j] += a_ndarray[i][k] * b_ndarray[k][j]
np.array(c_array3)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

# Problem 4
function, different code

In [53]:
def mat_mul(a,b):
    c_array = np.array([[sum(i*j for i,j in zip(a_rows,b_cols)) for b_cols in zip(*b_ndarray)] for a_rows in a_ndarray])
    return c_array
print(mat_mul(a_ndarray,b_ndarray))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# Problem 5
check the dimensions of the matrices

In [49]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

In [54]:
def mat_mul(a,b):
    a_row,a_col = a.shape
    b_row, b_col = b.shape
    if (a_col == b_row):
        c_array = np.array([[sum(i*j for i,j in zip(a_rows,b_cols)) for b_cols in zip(*b_ndarray)] for a_rows in a_ndarray])
        return c_array
    else:
        print("Can't perform matrix multiplication. Number of columns in A matrix should be equal the number of rows in B matrix. ")
print(mat_mul(d_ndarray,e_ndarray))

Can't perform matrix multiplication. Number of columns in A matrix should be equal the number of rows in B matrix. 
None


# Problem 6
matrix multiplication using transpose

In [70]:
def mat_mul(a,b):
    a_row,a_col = a.shape
    b_row, b_col = b.shape
    if (a_col == b_row):
        # resulting matrix dimension would be (a_row,b_col)
        c = np.zeros((a_row,b_col))
        b = np.transpose(b)
        # only uses 2 loops with transposed B matrix
        for i in range(len(a)):
            for j in range(len(b)):
                # instead of using similar statement like in Problem 3, just used dot product function
                c[i][j]= np.dot(a[i],b[j])
        return c
    else:
        print("Can't perform matrix multiplication. Number of columns in A matrix should be equal the number of rows in B matrix.")
print(mat_mul(a_ndarray,b_ndarray))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]
