# Problem 1
Enumeration of classes used so far <br/>
Now, you know that you must instantiate a class when you use it, and you know how to name a class. Based on this information, please answer what classes you have seen in the code you have used in previous assignments.

<b>Classes Series and DataFrame from pandas library</b> <br/>
pd.Series() <br/>
pd.DataFrame() <br/>
<b>Classes StandardScaler and LogisticRegression from scikit-learn library </b> <br/>
from sklearn.preprocessing import StandardScaler <br/>
from sklearn.linear_model import LogisticRegression <br/>
<b>Class LstedColormap from matlabplot library</b> <br/>
from matplotlib.colors import ListedColormap <br/>

# Problem 2
Enumeration of methods and instance variables used so far

From the last assignment, used <b> methods </b> <br/> 
fit() <br/>
transform() <br/>
predict() from classes ScandardScaler and LinearRegression class <br/>
Also there is methods like <br/>
array.sum() <br/> 
array.reshape() <br/>
df.info() or list.append(). <br/>
<b>Instance variables are: </b> <br/>
scaler.mean_ <br/>
array.shape <br/>
df.columns <br/>
also LinearRegression class has instance variables like, <br/>
reg.coef_ <br/>
reg.intercept.  

# Problem 3
Creating a standardized class by scratch

In [16]:
class ScratchStandardScaler():
    def __init__(self, copy=True, with_mean=True, with_std=True):
        self.with_mean = with_mean
        self.with_std = with_std
        self.copy = copy
        
    def fit(self, X):
        self.mean_ = np.mean(X,axis=0)
        self.var_ = np.var(X,axis=0)
        return self
    
    def transform(self, X):
        X_scaled = (X-self.mean_)/np.std(X,axis=0)
        return X_scaled

In [19]:
""" shows the result of the code using the class written above"""
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [ 4.86  3.31  1.45  0.22]
分散 : [ 0.0764  0.0849  0.0105  0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


In [20]:
""" shows the result of the code using StandardScaler class from scikit-learn"""
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scaler = StandardScaler()
scaler.fit(X)
print("平均 :", scaler.mean_)
print("分散 :", scaler.var_)
X_std = scaler.transform(X)
X_std

平均 : [ 4.86  3.31  1.45  0.22]
分散 : [ 0.0764  0.0849  0.0105  0.0056]


array([[ 0.86828953,  0.65207831, -0.48795004, -0.26726124],
       [ 0.14471492, -1.06391725, -0.48795004, -0.26726124],
       [-0.57885968, -0.37751902, -1.46385011, -0.26726124],
       [-0.94064699, -0.72071813,  0.48795004, -0.26726124],
       [ 0.50650222,  0.99527742, -0.48795004, -0.26726124],
       [ 1.95365143,  2.02487476,  2.43975018,  2.40535118],
       [-0.94064699,  0.3088792 , -0.48795004,  1.06904497],
       [ 0.50650222,  0.3088792 ,  0.48795004, -0.26726124],
       [-1.66422159, -1.40711636, -0.48795004, -0.26726124],
       [ 0.14471492, -0.72071813,  0.48795004, -1.60356745]])

# Problem 4
Creating a class that performs 4 arithmetic operations

In [35]:
""" subtraction, multiplication, and division 
non-numeric value such as a string or an array, an error should be raised """

class ArithmeticOperation():
    def __init__(self, value):
        if isinstance(value, int) or isinstance(value, float):
            self.value = value
            print("Inital value has been set".format(self.value))
        else:
            raise ValueError("Value is not int or float")
    def add(self, value2):
        if isinstance(value2, int) or isinstance(value2, float):
            self.value += value2
        else:
            raise ValueError("Value is not int or float")
    # substraction
    def sub(self,value2):   
        if isinstance(value2, int) or isinstance(value2, float):
            self.value -= value2
        else:
            raise ValueError("Value is not int or float")
    # multiplication
    def mul(self,value2):
        if isinstance(value2, int) or isinstance(value2, float):
            self.value *= value2
        else:
            raise ValueError("Value is not int or float")
    # division
    def div(self,value2):
        if isinstance(value2, int) or isinstance(value2, float):
            self.value /= value2
        else:
            raise ValueError("Value is not int or float")
    """
    Intial value set to 5 followed by operations +3, -4, *5, /10 
    results are printed as output 
    """
test = ArithmeticOperation(5)
print("value : {}".format(test.value))
test.add(3)
print("After adding 3 : {}".format(test.value))
test.sub(4)
print("After subtracting 4 : {}".format(test.value))
test.mul(5)
print("After multiplying by 5 : {}".format(test.value))
test.div(10)
print("After division of 10 : {}".format(test.value))

Inital value has been set
value : 5
After adding 3 : 8
After subtracting 4 : 4
After multiplying by 5 : 20
After division of 10 : 2.0


In [36]:
# it should raise an error if the value is not int or float
test.add(5)
print("After adding 5 : {}".format(test.value))
test.add('text')
print("After adding text : {}".format(test.value))

After adding 5 : 7.0


ValueError: Value is not int or float